Traceback (most recent call last):
  File "./frankenstein.py", line 476, in <module>
    frank.runlive()
  File "./frankenstein.py", line 420, in runlive
    self.check()
  File "./frankenstein.py", line 241, in check
    data = getFeed(self.symbol, self.maxlookback, self.interval)
  File "./frankenstein.py", line 67, in getFeed
    print 'last bar', data.index[-1], 'last processed bar', lastDate
  File "d:\anaconda2\lib\site-packages\pandas\indexes\base.py", line 1423, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
